name: bugbusterss
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.2
  flutter_svg: ^2.0.9
  firebase_database: ^11.3.10
  intl: ^0.18.1
  image_picker: ^1.1.2
  firebase_storage: ^12.1.0
  dropdown_search: ^5.0.0
  google_maps_flutter: ^2.5.0
  http: ^1.2.2
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/font/DMSans-Italic-VariableFont_opsz,wght.ttf
        - asset: assets/font/DMSans-VariableFont_opsz,wght.ttf
          weight: 400
          style: normal
    - family: OpenSans
      fonts:
        - asset: assets/font/Open_Sans/OpenSans-VariableFont_wdth,wght.ttf
          weight: 400
          style: normal
        - asset: assets/font/DMSans-VariableFont_opsz,wght.ttf
          weight: 700
          style: normal
  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#052659"
  image: assets/images/splash_icon.png

  android_12:
    image: assets/images/splash_icon.png
    color: "#052659"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/mosq.png" 