// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkz-zDKTZGy-qnD_SiD3MWV2_9PvApUvw',
    appId: '1:926905081367:web:57bcbd7493e3cbcaee8652',
    messagingSenderId: '926905081367',
    projectId: 'mosquifyy',
    authDomain: 'mosquifyy.firebaseapp.com',
    databaseURL: 'https://mosquifyy-default-rtdb.firebaseio.com',
    storageBucket: 'mosquifyy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs5r5eWIF9gZvELh4Sx7EdUrIRxwryZ2E',
    appId: '1:926905081367:android:d9a6a0c792c93d07ee8652',
    messagingSenderId: '926905081367',
    projectId: 'mosquifyy',
    databaseURL: 'https://mosquifyy-default-rtdb.firebaseio.com',
    storageBucket: 'mosquifyy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbvS6GAUaaN07ymr3XUae4KcdgnvvGImY',
    appId: '1:926905081367:ios:326a91ca06fdf299ee8652',
    messagingSenderId: '926905081367',
    projectId: 'mosquifyy',
    databaseURL: 'https://mosquifyy-default-rtdb.firebaseio.com',
    storageBucket: 'mosquifyy.firebasestorage.app',
    iosBundleId: 'com.example.mosquify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbvS6GAUaaN07ymr3XUae4KcdgnvvGImY',
    appId: '1:926905081367:ios:326a91ca06fdf299ee8652',
    messagingSenderId: '926905081367',
    projectId: 'mosquifyy',
    databaseURL: 'https://mosquifyy-default-rtdb.firebaseio.com',
    storageBucket: 'mosquifyy.firebasestorage.app',
    iosBundleId: 'com.example.mosquify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkz-zDKTZGy-qnD_SiD3MWV2_9PvApUvw',
    appId: '1:926905081367:web:0a37868186e13918ee8652',
    messagingSenderId: '926905081367',
    projectId: 'mosquifyy',
    authDomain: 'mosquifyy.firebaseapp.com',
    databaseURL: 'https://mosquifyy-default-rtdb.firebaseio.com',
    storageBucket: 'mosquifyy.firebasestorage.app',
  );

}